refactor(hyphenClient): simplify URL fetching logic
Hyphen/openfeature-provider-javascript-server pull request #18
Opened 2024-12-31 17:47 UTC by chrisllontop

… handling

2024-12-31 17:51 UTC, osbornm requested changes

2024-12-31 17:51 UTC, osbornm commented on src/hyphenClient.ts
> +        const url = `${baseUrl}${urlPath}`;
you should probably https://developer.mozilla.org/en-US/docs/Web/API/URL/URL rather than string concatination.

2025-01-01 19:02 UTC, osbornm requested changes

2025-01-01 19:02 UTC, osbornm commented on src/hyphenClient.ts
> +        baseUrl.pathname = basePath ? `${basePath}/${urlPath}` : urlPath;
Still don't know why we are doing string concatenation there are method in the URL object for this. please you those.

2025-01-02 15:02 UTC, chrisllontop commented on src/hyphenClient.ts
> +        baseUrl.pathname = basePath ? `${basePath}/${urlPath}` : urlPath;
@osbornm I’m working with URLs, but I’m also concatenating strings because I’m considering a scenario where a user configures something like https://domain.com/api/v1 as a custom URL. In this case, our endpoint call should resolve to something like https://domain.com/api/v1/toggle/evaluation, for example. Is it okay to handle these paths in the custom domain configuration, or should we only accept root-level domains or subdomains (e.g., https://domain.com or https://api.domain.com)?

If we were to only allow URLs without additional paths, then using something like new URL(path, baseUrl) would be sufficient to handle all cases. However, this approach might not work well if paths are part of the user’s custom URL configuration.

Should we accommodate paths in the custom URL, or strictly enforce root-level domains for simplicity and consistency?

2025-01-02 17:20 UTC, osbornm commented on src/hyphenClient.ts
> +        baseUrl.pathname = basePath ? `${basePath}/${urlPath}` : urlPath;
@chrisllontop I get your point but it seems like building a URL ourselves is prone to lots of issues (extra, slashes, encoding, etc.) It doesn't need to be perfect just seems like there should be a better way to validate the url.

2025-01-06 03:38 UTC, chrisllontop commented on src/hyphenClient.ts
> +        baseUrl.pathname = basePath ? `${basePath}/${urlPath}` : urlPath;
@osbornm I found https://nodejs.org/api/path.html#pathposix, please take a look my updated code.

2025-01-06 16:08 UTC, osbornm requested changes
POSIX is a unix thing not necessarily a web thing. Let's just go back to string concatenation for the release today.

2025-01-06 16:33 UTC, osbornm approved these changes

2025-01-06 16:36 UTC, merged